- hosts: localhost
  connection: local
  collections:
    - vmware.alb
  vars_files:
     variables.yml
  tasks:
  - include_vars: variables.yml
    #NSX-T Cloud connector user password change
  - name: Cloud connector user password change
    avi_cloudconnectoruser:
      controller: "{{ CONTROLLER_CLUSTER_IP }}"
      username: "{{ AVI_CREDENTIALS.username }}"
      password: "{{ AVI_CREDENTIALS.password }}"
      api_version: "{{ AVI_CREDENTIALS.api_version }}"
      avi_api_update_method: patch
      avi_api_patch_op: replace
      name: "{{ NSXT_CLOUDCONNECTORUSER }}"
      nsxt_credentials:
        password: "{{ NSXT_PASSWORD  }}"
    when:
      - NSXT_CLOUDCONNECTORUSER is defined
      - NSXT_PASSWORD is defined    
    #NSX-T Cloud vCenter user password change
  - name: Cloud connector user password change
    avi_cloudconnectoruser:
      controller: "{{ CONTROLLER_CLUSTER_IP }}"
      username: "{{ AVI_CREDENTIALS.username }}"
      password: "{{ AVI_CREDENTIALS.password }}"
      api_version: "{{ AVI_CREDENTIALS.api_version }}"
      avi_api_update_method: patch
      avi_api_patch_op: replace
      name: "{{ NSXT_VCENTER_CLOUDCONNECTORUSER }}"
      nsxt_credentials:
        password: "{{ NSXT_VCENTER_PASSWORD  }}"
    when:
      - NSXT_VCENTER_CLOUDCONNECTORUSER is defined
      - NSXT_VCENTER_PASSWORD is defined  
