
avi_config:
  poolgroup:
    - name: cd-app-poolgroup
      members:
        - pool_ref: "/api/pool?name=cd-app-pool-v1"
          ratio: 100
          deployment_state: IN_SERVICE

        #- pool_ref: "/api/pool?name=cd-app-pool-v2"
        #  ratio: 1
        #  deployment_state: OUT_OF_SERVICE
          #deployment_state: EVALUATION_IN_PROGRESS
      deployment_policy_ref: "/api/poolgroupdeploymentpolicy?name=cd-app-deployment-policy"

  poolgroupdeploymentpolicy:
    - name: cd-app-deployment-policy
      evaluation_duration: 60
      scheme: "CANARY"
      target_test_traffic_ratio: 100
      test_traffic_ratio_rampup: 100
      rules:
        - metric_id: l7_server.avg_resp_latency
          operator: CO_LE
        - metric_id: l7_server.avg_pool_error_responses
          operator: CO_LE
  pool:
    - name: cd-app-pool-v1
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server1 }}"
             type: 'V4'

    - name: cd-app-pool-v2
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server2 }}"
             type: 'V4'

    - name: cd-app-pool-v3
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server3 }}"
             type: 'V4'
  vsvip:
    - name: vsvip-cd-app-Default-Cloud
      vip:
      - enabled: true
        ip_address:
          addr: "{{ cd_app_vip }}"
          type: V4
        vip_id: '1'
        
  virtualservice:
    - name: cd-app
      services:
        - port: 80
      vsvip_ref: /api/vsvip/?name=vsvip-cd-app-Default-Cloud

      pool_group_ref: '/api/poolgroup?name=cd-app-poolgroup'
      cloud_ref: '/api/cloud?name=Default-Cloud'
      application_profile_ref: '/api/applicationprofile?name=System-HTTP'
      analytics_policy:
        metrics_realtime_update:
          duration: 0
          enabled: true
