---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Required Variables / SAML Settings
# Description: This are the main variables required for NSXT Cloud Password Change.
# --------------------------------------------------------------------

SAML_PROF_NAME: <SAML Profile Name>
SAML_METADATA: <SAML METADATA>
SAML_ENTITY_TYPE: <SAMl Entity Type - "AUTH_SAML_CLUSTER_VIP" | "AUTH_SAML_DNS_FQDN" | "AUTH_SAML_APP_VS> 
SAML_ORG_NAME: <SAML ORG Name> # If SAML_ENTITY_TYPE is set to "AUTH_SAML_APP_VS" then connent this line. 
SAML_DISPLAY_NAME: <SAML Display Name> # If SAML_ENTITY_TYPE is set to "AUTH_SAML_APP_VS" then connent this line. 
SAML_ORG_URL: <SAML ORG URL> # If SAML_ENTITY_TYPE is set to "AUTH_SAML_APP_VS" then connent this line. 
TECH_CONTACT_NAME: <SAML Tech Contact Name> # If SAML_ENTITY_TYPE is set to "AUTH_SAML_APP_VS" then connent this line. 
TECH_CONTACT_EMAIL: <SAML Tech Email Address> # If SAML_ENTITY_TYPE is set to "AUTH_SAML_APP_VS" then connent this line. 
SAML_FQDN: <SAML FQDN> # If SAML_ENTITY_TYPE is set to "AUTH_SAML_CLUSTER_VIP" or "AUTH_SAML_APP_VS" then connent this line.




# --------------------------------------------------------------------
# Required Variables / LDAP Settings
# Description: This are the main variables required for Avi User Password Change.
# --------------------------------------------------------------------

LDAP_PROF_NAME: <LDAP Profile Name>
LDAP_SERVER: [<Comma Seperated FQDN/IP List] #Ex. [1.1.1.1,2.2.2.2,3.3.3.3] or [ad1.avi.com,ad2.avi.com]
LDAP_PORT: <LDAP Port>
LDAP_SEC_MODE: <LDAP Security Mode - AUTH_LDAP_SECURE | AUTH_LDAP_SECURE_NONE>
BASE_DN: <LDAP Base DN>
ADMIN_BIND_DN: <LDAP Admin Bind DN>
ADMIN_BIND_PASSWORD: <LDAP Admin Bind Password>
USER_SEARCH_DN: <LDAP User Search DN>
USER_SEARCH_SCOPE: <LDAP User Search Scope - AUTH_LDAP_SCOPE_BASE | AUTH_LDAP_SCOPE_ONE | AUTH_LDAP_SCOPE_SUBTREE>
USER_ID_ATTRIBUTE: <LDAP User ID Attribute>
GROUP_SEARCH_DN: <LDAP Group Search DN>
GROUP_MEM_ATTR: <LDAP Group Member Attribute> # Default is set to "member"
GROUP_SEARCH_SCOPE: <LDAP Group Search Scope - AUTH_LDAP_SCOPE_BASE | AUTH_LDAP_SCOPE_ONE | AUTH_LDAP_SCOPE_SUBTREE>
GROUP_MEM_FULL_DN: <LDAP Group Member full DN - true | false> # Default is set to true
GROUP_FILTER: <LDAP Group Filter> # Default is set to "(objectClass=*)"
IGNORE_REF: <LDAP Ignore Ref - true | false> # Default is set to false

# --------------------------------------------------------------------
# Required Variables / Group Mapping
# Description: This are the main variables required for Avi User Password Change.
# --------------------------------------------------------------------

AUTH_MAPPING:  
 - {group: "<LDAP Group Name>", tenant: "<Avi Tenant Name>", role: "<Avi Role Name>"}
- # Additional Array elements can be added below