{
 "title": "02-Service Engines Total",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "location", "query": "network-script.avi.*" },
   { "name": "environment", "query": "network-script.avi.$location.*" },
   {
    "name": "device",
    "query": "network-script.avi.$location.$environment.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Total SE Average Bandwidth (5min avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'totalbandwidth')"
    }
   ]
  },
  {
   "title": "Top 5 SE - Average Bandwidth (5min avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth, 5), 6)"
    }
   ]
  },
  {
   "title": "Top 5 - SE CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_cpu_usage, 5), 6)"
    }
   ]
  },
  {
   "title": "Top VS SSL TPS Per SE - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.virtualservice_stats.*.l7_client_avg_ssl_handshakes_new, 10), 8, 6)"
    }
   ]
  },
  {
   "title": "VS per SE - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.vs_count, 10), 6)"
    }
   ]
  },
  {
   "title": "Lowest 5 - SE Healthscores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(lowestAverage(sortByMinima(network-script.avi.$location.$environment.$device.serviceengine.*.healthscore), 5), 6)"
    }
   ]
  },
  {
   "title": "Number of Service Engines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.count, 5)"
    }
   ]
  },
  {
   "title": "SE RX PPS  - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_rx_pkts, 10), 6)"
    }
   ]
  },
  {
   "title": "Connection Memory Usage - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_connection_mem_usage, 10), 6)"
    }
   ]
  },
  {
   "title": "SE CPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_connections, 10), 6)"
    }
   ]
  },
  {
   "title": "VS Capacity Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.vs_capacity_used, 10), 6)"
    }
   ]
  },
  {
   "title": "Top VS Client BW Per SE - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.virtualservice_stats.*.l4_client_avg_bandwidth, 10), 8, 6)"
    }
   ]
  },
  {
   "title": "SE Missed Heartbeats - Top 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.missed_heartbeats, 5), 6)"
    }
   ]
  }
 ]
}