apiVersion: v1
kind: ClusterRole
metadata:
  name: avirole
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - routes/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - securitycontextconstraints
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
