---
- gather_facts: 'false'
  hosts: all
  roles:
  - con_csp_default_gw: 10.128.2.1
    con_csp_disk_size: 100
    con_csp_memory_mb: 24576
    con_csp_mgmt_ip: 10.128.2.191
    con_csp_mgmt_mask: 255.255.255.0
    con_csp_num_cpu: 6
    con_csp_password: "{{csp_password}}"
    con_csp_qcow_image_file: /tmp/Smoke-Ctlr-I.qcow2
    con_csp_service_name: Smoke-Ctlr-I
    con_csp_user: admin
    con_csp_vnics:
    - network_name: enp12s0f0
      nic: 0
      tagged: 'false'
      type: access
    con_deploy_type: csp
    role: avinetworks.avicontroller-csp
