---
- hosts: all
  gather_facts: false
  roles:
    - role: avinetworks.avicontroller
      con_deploy_type: csp
      con_csp_user: admin
      con_csp_password: AviCsp@2100
      con_csp_qcow_image_file: eric-controller.qcow2
      con_csp_mgmt_ip: 10.128.2.18
      con_csp_mgmt_mask: 255.255.255.0
      con_csp_default_gw: 10.128.2.1
      con_csp_service_name: eric-controller1
      con_csp_memory: 16384
