{
 "title": "02-Service Engines Total",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\" WHERE location =~ /$location/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"avicontroller\" WHERE location =~ /$location/ AND environment =~ /$environment/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total SE Average Bandwidth (5min avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "total bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'totalbandwidth')"
    }
   ]
  },
  {
   "title": "Top 5 SE - Average Bandwidth (5min avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth, 5), 6)"
    }
   ]
  },
  {
   "title": "Top 5 - SE CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_cpu_usage, 5), 6)"
    }
   ]
  },
  {
   "title": "Top VS SSL TPS Per SE - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name : $tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.virtualservice_stats.*.l7_client_avg_ssl_handshakes_new, 10), 8, 6)"
    }
   ]
  },
  {
   "title": "VS per SE - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vs_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_vs_count" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.vs_count, 10), 6)"
    }
   ]
  },
  {
   "title": "Lowest 5 - SE Healthscores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthscore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "bottom" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_healthscore" }
     ],
     "target": "aliasByNode(lowestAverage(sortByMinima(network-script.avi.$location.$environment.$device.serviceengine.*.healthscore), 5), 6)"
    }
   ]
  },
  {
   "title": "Number of Service Engines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_count" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.count, 5)"
    }
   ]
  },
  {
   "title": "SE RX PPS  - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_rx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_rx_pkts, 10), 6)"
    }
   ]
  },
  {
   "title": "Connection Memory Usage - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_connection_mem_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_connection_mem_usage, 10), 6)"
    }
   ]
  },
  {
   "title": "SE CPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_connections, 10), 6)"
    }
   ]
  },
  {
   "title": "VS Capacity Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vs_capacity_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_capacity" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.vs_capacity_used, 10), 6)"
    }
   ]
  },
  {
   "title": "Top VS Client BW Per SE - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name : $tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.virtualservice_stats.*.l4_client_avg_bandwidth, 10), 8, 6)"
    }
   ]
  },
  {
   "title": "SE Missed Heartbeats - Top 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "missed_heartbeats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "serviceengine_missed_heartbeats"
      }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.missed_heartbeats, 5), 6)"
    }
   ]
  }
 ]
}