{
 "title": "04-Virtual Services Total",
 "tags": [
  "avi",
  "network"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\" WHERE location =~ /$location/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"avicontroller\" WHERE location =~ /$location/ AND environment =~ /$environment/"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 - Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_bandwidth, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_new_established_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 Lowest VS Healthscores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthscore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "bottom" }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_healthscore" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(lowestCurrent(network-script.avi.$location.$environment.$device.virtualservice.*.healthscore, 10), 6)"
    }
   ]
  },
  {
   "title": "SSL TPS - Top 10",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l7_client_avg_ssl_handshakes_new, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_complete_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_complete_conns, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_rx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_rx_pkts, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_tx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_tx_pkts, 10), 6)"
    }
   ]
  }
 ]
}