{
 "title": "Avi - Virtual Services-Sizing-Metrics",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\" WHERE location =~ /$location/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"avicontroller\" WHERE location =~ /$location/ AND environment =~ /$environment/"
   },
   {
    "name": "vs",
    "query": "SHOW TAG VALUES WITH KEY = \"vs_name\" WHERE location =~ /$location/ AND environment =~ /$environment/ AND avicontroller =~ /$device/"
   }
  ]
 },
 "panels": [
  {
   "title": "End to End Timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Client RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_total_rtt",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"l4_client.avg_total_rtt\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"environment\" =~ /^$environment$/ AND \"location\" =~ /^$location$/ AND \"vs_name\" =~ /^$vs$/ AND \"metric_type\" = 'virtualservice_metrics') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_application_response_time)"
    },
    {
     "alias": "Server RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_total_rtt",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"l4_server.avg_total_rtt\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"environment\" =~ /^$environment$/ AND \"location\" =~ /^$location$/ AND \"vs_name\" =~ /^$vs$/ AND \"metric_type\" = 'virtualservice_metrics') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_client_data_transfer_time)"
    },
    {
     "alias": "App Response",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_server.avg_application_response_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_total_rtt)"
    },
    {
     "alias": "Data Transfer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_client_data_transfer_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_server_avg_total_rtt)"
    }
   ]
  },
  {
   "title": "Sum all Requests - WAF eval/matched/rejected/bypass",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_waf_matched",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_waf_matched)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_waf_evaluated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_waf_evaluated)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_waf_rejected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_waf_rejected)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_waf_disabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_waf_disabled)"
    }
   ]
  },
  {
   "title": "Percentage GET/POST/BYPASS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.pct_get_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_pct_get_reqs)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.pct_post_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_pct_post_reqs)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.pct_waf_disabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_pct_waf_disabled)"
    }
   ]
  },
  {
   "title": "Sum all Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.sum_total_responses",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_sum_total_responses)"
    }
   ]
  },
  {
   "title": "Average Post Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_post_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_post_bytes)"
    }
   ]
  },
  {
   "title": "Average Header Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_http_headers_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_http_headers_count)"
    }
   ]
  },
  {
   "title": "Average Header Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_http_headers_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_http_headers_bytes)"
    }
   ]
  },
  {
   "title": "Average Parameter Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_http_params_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_http_params_count)"
    }
   ]
  },
  {
   "title": "Average URI Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_uri_length",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_uri_length)"
    }
   ]
  }
 ]
}