---
#test ansible script for ec2 deploy
- hosts: localhost
  connection: local
  vars:
    controller: 10.10.27.90
    username: admin
    password: AviNetworks123!
  roles:
    - roles: avinetworks.avisdk
  tasks:
    - name: "Create EC2 instance"
      ec2:
        key_name: eanderson-key
        instance_type: t2.nano
        region: us-west-2
        image: ami-f847bd98
        group_id: sg-a9a00fcd
        wait: no
        vpc_subnet_id: subnet-70ea5229
        assign_public_ip: yes
        instance_tags:
          Name: srv01
          exact_count: 1
        count_tag:
          Name: srv01
      register: srv01
    - debug: msg="{{ srv01 }}"
    - avi_pool:
        controller: "{{ controller }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: testpool2
        description: testpool2
        state: present
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: 10.90.130.7
              type: V4
      register: pool
    - debug: msg="{{ pool.obj.url }}"
    - avi_virtualservice:
        controller: "{{ controller }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        services:
          - port: 443
            enable_ssl: true
        ssl_profile_ref: '/api/sslprofile?name=System-Standard'
        application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
        ssl_key_and_certificate_refs:
          - '/api/sslkeyandcertificate?name=System-Default-Cert'
        ip_address:
          addr: 10.90.131.103
          type: V4
        pool_ref: "{{ pool.obj.url }}"
        name: newtestvs
