# This is playbook for an application.
# This can invoke any of the avi roles like application, profile or cloud
#
---
- hosts: localhost
  connection: local
  vars:
    api_version: 17.1.2
    app_name: complex_app
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Setting up Application
      debug: msg="{{ app_name }}"

    - name: Load vars
      include_vars:
        file: "{{ site_dir }}/vars/creds.yml"

    - name: Compose Avi Config
      set_fact:
        avi_config_var:
          pool:
            - name: "{{ app_name}}-pool"
              lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
              servers:
                - ip:
                     addr: "{{ pool_server1 }}"
                     type: 'V4'
                - ip:
                     addr: "{{ pool_server2 }}"
                     type: 'V4'
          virtualservice:
            - name: "{{app_name}}"
              services:
                - port: 80
              pool_ref: "/api/pool?name={{app_name}}-pool"
              vip:
                - ip_address:
                    addr: "{{ complex_app_vip }}"
                    type: 'V4'
                  vip_id: '1'

    - name: Avi Application | Setup complex_app
      include_role:
        name: avinetworks.aviconfig
        avi_config: "{{avi_config_var}}"
