{
 "title": "03-Service Engine Specific",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "location", "query": "network-script.avi.*" },
   { "name": "environment", "query": "network-script.avi.$location.*" },
   {
    "name": "device",
    "query": "network-script.avi.$location.$environment.*"
   },
   {
    "name": "serviceengine",
    "query": "network-script.avi.$location.$environment.$device.serviceengine.*"
   }
  ]
 },
 "panels": [
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_connections"
    }
   ]
  },
  {
   "title": "Concurrent Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l4_client_max_open_conns)"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_cpu_usage"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.healthscore, 6)"
    }
   ]
  },
  {
   "title": "SE Average Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_tx_bytes, 8), 'avg tx bw')"
    },
    {
     "target": "alias(scale(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_rx_bytes, 8), 'avg rx bw')"
    }
   ]
  },
  {
   "title": "SE CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "VS per SE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.vs_count, 6)"
    }
   ]
  },
  {
   "title": "SE Healthscore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.healthscore, 6)"
    }
   ]
  },
  {
   "title": "SE Dispatcher CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.dispatcher_usage.se_dp0)"
    }
   ]
  },
  {
   "title": "SE RX PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "SE TX PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_tx_pkts, 6)"
    }
   ]
  },
  {
   "title": "SE CPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_connections, 6)"
    }
   ]
  },
  {
   "title": "VS Capacity Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.vs_capacity_used, 6)"
    }
   ]
  },
  {
   "title": "SE Missed Heartbeats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.missed_heartbeats, 6)"
    }
   ]
  },
  {
   "title": "Per VS Client BW - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l4_client_avg_bandwidth, 10), 8)"
    }
   ]
  },
  {
   "title": "Per VS SSL TPS - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l7_client_avg_ssl_handshakes_new, 10), 8)"
    }
   ]
  },
  {
   "title": "Connection Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_connection_mem_usage, 6)"
    }
   ]
  },
  {
   "title": "Per VS - Client Side Open Conns - Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l4_client_max_open_conns, 10), 8)"
    }
   ]
  }
 ]
}