{
 "title": "04-Virtual Services Total",
 "tags": [
  "avi",
  "network"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "location", "query": "network-script.avi.*" },
   { "name": "environment", "query": "network-script.avi.$location.*" },
   {
    "name": "device",
    "query": "network-script.avi.$location.$environment.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 - Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_bandwidth, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 Lowest VS Healthscores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(lowestCurrent(removeEmptySeries(network-script.avi.$location.$environment.$device.virtualservice.*.healthscore, 0), 10), 6)"
    }
   ]
  },
  {
   "title": "SSL TPS - Top 10",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l7_client_avg_ssl_handshakes_new, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_complete_conns, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_rx_pkts, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_tx_pkts, 10), 6)"
    }
   ]
  }
 ]
}