############################################################
# Dockerfile to build python avi-monitor script container
# Based on alpine:edge
############################################################

# Set the base image to alpine:edge
FROM alpine:edge

# Set the working directory
WORKDIR /usr/src/avi

# File Author / Maintainer
MAINTAINER mkarnowski@avinetworks.com


################## BEGIN INSTALLATION ######################

# Set Docker environment variable
ENV EN_DOCKER=True


# Install python requirements
RUN apk add --no-cache python python-dev py-pip
RUN pip install --no-cache-dir requests


# Copy scripts to directory
COPY "avimetrics.py" "/usr/src/avi"
COPY "avi_controllers.json" "/usr/src/avi"
COPY "metrics_endpoints.py" "/usr/src/avi"
COPY "datadog.json" "/usr/src/avi"
COPY "graphite_host.json" "/usr/src/avi"
COPY "splunk_host.json" "/usr/src/avi"
COPY "appdynamics_http.json" "/usr/src/avi"
COPY "influxdb.json" "/usr/src/avi"


# Execute script
CMD ["python", "/usr/src/avi/avimetrics.py"]
