---
[all:vars]
ansible_connection=ssh
ansible_ssh_private_key_file=~/.ssh/gcp_rsa
ansible_ssh_user=grastogi
ansible_processor_cores=4
ansible_processor_count=4
ansible_become=yes
#ansible_ssh_pass=avi123
[bm]
#35.202.209.61
35.225.121.166