---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Required Variables / Controller Deployments
# Description: This are the main variables required for controller deployments.
# --------------------------------------------------------------------

# --------------------------------------------------------------------
# Enviroment Variables / Controller Deployments
# Description: You only have to apply variables on the installation type you desire.
# --------------------------------------------------------------------

# Upgrade files info
BASE_UPGRADE_FILE: <Base Upgrade Package File Location>
BASE_UPGRADE_VERSION: <Base Upgrade Package Version> #Ex. 22.1.3
PATCH_UPGRADE_FILE: <Patch Upgrade Package File Location>
PATCH_UPGRADE_VERSION: <Patch Upgrade Package Version> #Ex. 2p1


