---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"


# --------------------------------------------------------------------
# Required Variables / NSXT Cloud Connector
# Description: This are the main variables required for Avi User Password Change.
# --------------------------------------------------------------------

CLOUD_NAME: <Cloud Connector Name>
DHCP: <Management DHCP Setting - true|false> #Default is false
CLOUD_PREFIX: <NSXT Object Name Prefix>
NSXT_DATA_T1_SEG:  # Comment if Data Transport Zone is type VLAN
 - {T1: "<T1 Name>", SEG: "<Segment Name>"} # Comment if Data Transport Zone is type VLAN
 - {T1: "<T1 Name>", SEG: "<Segment Name>"} # Comment if Data Transport Zone is type VLAN
 - # Additional Array elements can be added below
NSXT_DATA_VLAN_SEG:  # Comment if Data Transport Zone is type Overlay
 - {SEG: "<Segment Name>"} # Comment if Data Transport Zone is type Overlay
 - {SEG: "<Segment Name>"} # Comment if Data Transport Zone is type Overlay
 - # Additional Array elements can be added below