---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Required Variables / NSX-T Password Change
# Description: This are the main variables required for NSXT Cloud Password Change.
# --------------------------------------------------------------------

NSXT_CLOUDCONNECTORUSER: <NSXT Cloud Connector User Object Name>
NSXT_USERNAME: <NSXT Username>
NSXT_PASSWORD: <NSXT Password>
NSXT_VCENTER_CLOUDCONNECTORUSER: <vCenter Cloud Connector User Object Name>
NSXT_VCENTER_USERNAME: <vCenter Username>
NSXT_VCENTER_PASSWORD: <vCenter Password>



# --------------------------------------------------------------------
# Required Variables / NSXT Cloud Connector
# Description: This are the main variables required for Avi User Password Change.
# --------------------------------------------------------------------

CLOUD_NAME: <NSXT CLoud Connector Name>
DHCP: <Management DHCP Setting - true|false> #Default is false
CLOUD_PREFIX: <NSXT Object Name Prefix>
NSXT_MANAGER: <NSXT Manager FQDN/IP Address>
NSXT_MGMT_TZ: <MGMT Transport Zone Name>
NSXT_MGMT_T1: <MGMT T1 Name> # Comment if MGMT TZ is type VLAN
NSXT_MGMT_SEG: <MGMT Segment Name>
NSXT_DATA_TZ: <Data Transport Zone Name>
NSXT_DATA_T1_SEG:  # Comment if Data Transport Zone is type VLAN
 - {T1: "<T1 Name>", SEG: "<Segment Name>"} # Comment if Data Transport Zone is type VLAN
 - {T1: "<T1 Name>", SEG: "<Segment Name>"} # Comment if Data Transport Zone is type VLAN
 - # Additional Array elements can be added below
NSXT_DATA_VLAN_SEG:  # Comment if Data Transport Zone is type Overlay
 - {SEG: "<Segment Name>"} # Comment if Data Transport Zone is type Overlay
 - {SEG: "<Segment Name>"} # Comment if Data Transport Zone is type Overlay
 - # Additional Array elements can be added below

# --------------------------------------------------------------------
# Required Variables / NSXT Cloud Connector
# Description: This are the main variables required for Avi User Password Change.
# --------------------------------------------------------------------

VCENTER_CONN_NAME: <vCenter Connection Object Name>
VCENTER_HOST: <vCenter Server FQDN/IP Address>
CONTENT_LIBRARY: <Content Library Name>