---
- hosts: localhost
  connection: local
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Cloud Connector Configuration
      avi_cloud:
        name: "{{ cloud_name }}"
        avi_credentials: "{{ avi_credentials }}"
        vtype: CLOUD_VCENTER
        dhcp_enabled: false
        license_type: "LIC_CORES"
        vcenter_configuration:
          username: "{{ vcenter_user }}"
          password: "{{ vcenter_password }}"
          datacenter: "{{ datacenter }}"
          management_network: "{{ '/api/vimgrnwruntime/?name=' + se_mgmt_portgroup }}"
          privilege: "WRITE_ACCESS"
          vcenter_url: "{{ vcenter_host }}"
    - pause:
        minutes: 1
      name: Cloud Preparing Integration
    - name: Configure SE MGMT Networks
      avi_network:
        name: "{{ se_mgmt_portgroup }}"
        avi_credentials: "{{ avi_credentials }}"
        cloud_ref: "{{'/api/cloud?name='+ cloud_name }}"
        dhcp_enabled: false
        configured_subnets:
          - prefix:
              mask: '{{ se_mgmt_mask }}'
              ip_addr:
                type: V4
                addr: '{{ se_mgmt_network }}'
            static_ranges:
            - begin:
                type: V4
                addr: '{{ se_mgmt_start_range }}'
              end:
                type: V4
                addr: '{{ se_mgmt_end_range }}'
    - name: Configure SE MGMT DFGW
      avi_vrfcontext:
        avi_credentials: "{{ avi_credentials }}"
        cloud_ref: "{{'/api/cloud?name='+ cloud_name }}"
        name: "management"
        static_routes:
        - route_id: "1"
          prefix:
            mask: 0
            ip_addr: 
              type: "V4"
              addr: "0.0.0.0"
          next_hop:
            type: "V4"
            addr: "{{ se_default_gateway }}"
    - name: Cloud Setup
      avi_cloud:
        name: "{{ cloud_name }}"
        avi_credentials: "{{ avi_credentials }}"
        vtype: CLOUD_VCENTER
        dhcp_enabled: false
        license_type: "LIC_CORES"
        vcenter_configuration:
          username: "{{ vcenter_user }}"
          password: "{{ vcenter_password }}"
          datacenter: "{{ datacenter }}"
          management_network: "{{ '/api/vimgrnwruntime/?name=' + se_mgmt_portgroup }}"
          privilege: "WRITE_ACCESS"
          vcenter_url: "{{ vcenter_host }}"