---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Required Variables / Cert Renewal
# Description: This are the main variables required for renewing a certificate.
# --------------------------------------------------------------------

# New Certificate file
CERT_NAME: <Certificate Object Name>
NEW_CERT_FILE: <Certificate file location>



