{
 "title": "Avi-Virtual Services Total",
 "tags": [ "avi" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({type=\"virtualservice\"},instance)"
   },
   {
    "name": "tenant",
    "query": "label_values({type=\"virtualservice\",instance=~\"$instance\"},tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 - Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,avi_l4_client_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_bandwidth, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,avi_l4_client_avg_new_established_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 Lowest VS Healthscores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10,avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(lowestCurrent(network-script.avi.$location.$environment.$device.virtualservice.*.healthscore, 10), 6)"
    }
   ]
  },
  {
   "title": "SSL TPS - Top 10",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,avi_l7_client_avg_ssl_handshakes_new{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l7_client_avg_ssl_handshakes_new, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,avi_l4_client_avg_complete_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_complete_conns, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,avi_l4_client_avg_rx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_rx_pkts, 10), 6)"
    }
   ]
  },
  {
   "title": "Top 10 - TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,avi_l4_client_avg_tx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\"})",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(highestMax(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_tx_pkts, 10), 6)"
    }
   ]
  }
 ]
}