{
 "title": "Avi-Virtual Services Specific",
 "tags": [ "avi" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({type=\"serviceengine\"},instance)"
   },
   {
    "name": "tenant",
    "query": "label_values({type=\"virtualservice\",instance=~\"$instance\"},tenant)"
   },
   {
    "name": "virtualservice",
    "query": "label_values({instance=\"$instance\", tenant=\"$tenant\",type=\"virtualservice\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_l4_client_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_l4_client_avg_new_established_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns"
    }
   ]
  },
  {
   "title": "Concurrent Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_l4_client_avg_complete_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns"
    }
   ]
  },
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_l7_client_avg_ssl_handshakes_new{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore)"
    }
   ]
  },
  {
   "title": "Client Side Timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_total_rtt{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "Client RTT",
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_total_rtt, 'Client RTT')"
    },
    {
     "expr": "avi_l7_client_avg_client_data_transfer_time{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "Data Transfer",
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_client_data_transfer_time, 'Data Transfer')"
    }
   ]
  },
  {
   "title": "VS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_new_established_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns, 6)"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_complete_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns, 6)"
    }
   ]
  },
  {
   "title": "RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_rx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_tx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_tx_pkts, 6)"
    }
   ]
  },
  {
   "title": "VS Healthscore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore, 6)"
    }
   ]
  },
  {
   "title": "SSL Statistics /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l7_client_avg_ssl_handshakes_new{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "l7_client_avg_ssl_handshakes_new",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_handshakes_new)"
    },
    {
     "expr": "avi_l7_client_avg_ssl_connections{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "l7_client_avg_ssl_connections",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_connections)"
    }
   ]
  },
  {
   "title": "Average Client Lossy Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_avg_lossy_connections{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_lossy_connections)"
    }
   ]
  },
  {
   "title": "4xx 5xx Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l7_client_avg_resp_4xx_avi_errors{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "l7_client_avg_resp_4xx_avi_errors",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx_avi_errors)"
    },
    {
     "expr": "avi_l7_client_avg_resp_5xx_avi_errors{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "l7_client_avg_resp_5xx_avi_errors",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_5xx_avi_errors)"
    },
    {
     "expr": "avi_l7_client_avg_resp_4xx{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "l7_client_avg_resp_4xx",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx)"
    },
    {
     "expr": "avi_l7_client_avg_resp_5xx{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "l7_client_avg_resp_5xx",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_5xx)"
    }
   ]
  },
  {
   "title": "Client Side Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_max_open_conns{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_max_open_conns)"
    }
   ]
  },
  {
   "title": "Virtual Service ApDex  Values",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_l4_client_apdexc{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{__name__}}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_apdexc)"
    },
    {
     "expr": "avi_l7_client_apdexr{instance=~\"$instance\", tenant=~\"$tenant\",type=\"virtualservice\",name=\"$virtualservice\"}",
     "legendFormat": "{{__name__}}",
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_apdexr)"
    }
   ]
  }
 ]
}