{
 "title": "Avi-Controller",
 "tags": [ "avi" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({type=\"serviceengine\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Virtualservices",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avi_controller_stats_avg_num_active_vs{instance=\"$instance\", type=\"controller\"})"
    }
   ]
  },
  {
   "title": "Number of Backend Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avi_controller_stats_avg_num_backend_servers{instance=\"$instance\", type=\"controller\"})"
    }
   ]
  },
  {
   "title": "Number of Service Engines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (name) ({instance=\"$instance\",type=\"serviceengine\"}))"
    }
   ]
  },
  {
   "title": "Controller CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_controller_stats_avg_cpu_usage{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "Controller Mem%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_controller_stats_avg_mem_usage{instance=~\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_mem_usage, 6)"
    }
   ]
  },
  {
   "title": "Average Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avi_controller_stats_avg_disk_usage{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avi_controller_stats_avg_disk_write_bytes{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avi_controller_stats_avg_disk_read_bytes{instance=\"$instance\", type=\"controller\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}