{
 "title": "Avi-Service Engine Specific",
 "tags": [ "avi" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({type=\"serviceengine\"},instance)"
   },
   {
    "name": "tenant",
    "query": "label_values({type=\"serviceengine\",instance=~\"$instance\"},tenant)"
   },
   {
    "name": "serviceengine",
    "query": "label_values({instance=~\"$instance\", tenant=\"$tenant\",type=\"serviceengine\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "SE Healthscore",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.healthscore, 6)"
    }
   ]
  },
  {
   "title": "SE CPU%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avi_se_stats_avg_cpu_usage{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_healthscore_health_score_value{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.healthscore, 6)"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avi_se_stats_avg_cpu_usage{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "target": "network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_cpu_usage"
    }
   ]
  },
  {
   "title": "SE Average Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avi_se_if_avg_bandwidth{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avi_se_if_avg_tx_bytes{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"} * 8\n",
     "legendFormat": "avg tx bw",
     "target": "alias(scale(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_tx_bytes, 8), 'avg tx bw')"
    },
    {
     "expr": "avi_se_if_avg_rx_bytes{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"} * 8\n",
     "legendFormat": "avg rx bw",
     "target": "alias(scale(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_rx_bytes, 8), 'avg rx bw')"
    }
   ]
  },
  {
   "title": "SE RX PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "avi_se_if_avg_rx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "SE TX PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "avi_se_if_avg_tx_pkts{instance=~\"$instance\", tenant=~\"$tenant\",type=\"serviceengine\",name=\"$serviceengine\"}",
     "legendFormat": "{{name}}",
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_tx_pkts, 6)"
    }
   ]
  }
 ]
}