---
- name: Update the SSL system configuration to have the latest SSL certificate
  avi_systemconfiguration:
    avi_api_update_method: patch
    avi_api_patch_op: replace
    avi_credentials: "{{ avi_credentials }}"
    api_version: 17.2.13
    tenant: admin
    portal_configuration:
      sslkeyandcertificate_refs:
        - "/api/sslkeyandcertificate?name={{ name }}"
