---
- name: GSLB Config | Make sure GSLB Role exists
  include_tasks: add_gslb_role.yml

- name: GSLB Config | Generate Password for GSLB User
  set_fact:
    gslbadmin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation') }}"
    ipaddr_fqdntype: DNS
    ipaddr_iptype: V4
  no_log: true

- name: GSLB Config | Create GSLB User
  avi_user:
    avi_credentials: "{{ avi_credentials }}"
    api_version: 17.2.13
    name: gslbadmin
    obj_username: gslbadmin
    obj_password: "{{ gslbadmin_password }}"
    access:
      - role_ref: "/api/role?name=GSLB-Admin"
        tenant_ref: "/api/tenant?name=admin"
    user_profile_ref: "/api/useraccountprofile?name=No-Lockout-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"

- name: GSLB Config | Verify GSLB site configuration
  avi_api_session:
    avi_credentials: "{{ avi_credentials }}"
    api_version: 17.2.13
    http_method: post
    path: gslbsiteops/verify
    data:
      name: filler_till_api_fixed
      username: gslbadmin
      password: "{{ gslbadmin_password }}"
      port: 443
      ip_addresses:
        - type: "{% if controller_ip | ipaddr %}{{ ipaddr_iptype }}{% else %}{{ ipaddr_fqdntype }}{% endif %}"
          addr: "{{ controller_ip }}"
  register: gslb_verify

- name: GSLB Config | Create the GSLB Site
  avi_gslb:
    avi_credentials: "{{ avi_credentials }}"
    api_version: 17.2.13
    name: Default
    tenant_ref: "/api/tenant?name=admin"
    leader_cluster_uuid: "{{ gslb_verify.obj.rx_uuid }}"
    sites:
      - cluster_uuid: "{{ gslb_verify.obj.rx_uuid }}"
        enabled: true
        port: 443
        member_type: GSLB_ACTIVE_MEMBER
        ip_addresses:
          - type: "{% if controller_ip | ipaddr %}{{ ipaddr_iptype }}{% else %}{{ ipaddr_fqdntype }}{% endif %}"
            addr: "{{ controller_ip }}"
        name: "{{ deployment_name }}"
        username: gslbadmin
        password: "{{ gslbadmin_password }}"
    state: present
