---
- name: Create Customer-Admin role
  avi_role:
    avi_credentials: "{{ avi_credentials }}"
    api_version: 17.2.13
    name: Customer-Admin
    privileges:
    - resource: PERMISSION_VIRTUALSERVICE
      type: WRITE_ACCESS
    - resource: PERMISSION_POOL
      type: WRITE_ACCESS
    - resource: PERMISSION_POOLGROUP
      type: WRITE_ACCESS
    - resource: PERMISSION_HTTPPOLICYSET
      type: WRITE_ACCESS
    - resource: PERMISSION_NETWORKSECURITYPOLICY
      type: WRITE_ACCESS
    - resource: PERMISSION_NETWORKPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_APPLICATIONPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_APPLICATIONPERSISTENCEPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_HEALTHMONITOR
      type: WRITE_ACCESS
    - resource: PERMISSION_ANALYTICSPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_IPAMDNSPROVIDERPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_IPADDRGROUP
      type: WRITE_ACCESS
    - resource: PERMISSION_STRINGGROUP
      type: WRITE_ACCESS
    - resource: PERMISSION_VSDATASCRIPTSET
      type: WRITE_ACCESS
    - resource: PERMISSION_MICROSERVICEGROUP
      type: WRITE_ACCESS
    - resource: PERMISSION_SSLPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_AUTHPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_PKIPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_SSLKEYANDCERTIFICATE
      type: WRITE_ACCESS
    - resource: PERMISSION_CERTIFICATEMANAGEMENTPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_ALERTCONFIG
      type: WRITE_ACCESS
    - resource: PERMISSION_ALERT
      type: WRITE_ACCESS
    - resource: PERMISSION_ACTIONGROUPCONFIG
      type: WRITE_ACCESS
    - resource: PERMISSION_ALERTSYSLOGCONFIG
      type: WRITE_ACCESS
    - resource: PERMISSION_ALERTEMAILCONFIG
      type: WRITE_ACCESS
    - resource: PERMISSION_SNMPTRAPPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_TRAFFIC_CAPTURE
      type: WRITE_ACCESS
    - resource: PERMISSION_CLOUD
      type: WRITE_ACCESS
    - resource: PERMISSION_SERVICEENGINE
      type: WRITE_ACCESS
    - resource: PERMISSION_SERVICEENGINEGROUP
      type: WRITE_ACCESS
    - resource: PERMISSION_NETWORK
      type: WRITE_ACCESS
    - resource: PERMISSION_VRFCONTEXT
      type: WRITE_ACCESS
    - resource: PERMISSION_SYSTEMCONFIGURATION
      type: WRITE_ACCESS
    - resource: PERMISSION_CONTROLLER
      type: NO_ACCESS
    - resource: PERMISSION_REBOOT
      type: NO_ACCESS
    - resource: PERMISSION_UPGRADE
      type: NO_ACCESS
    - resource: PERMISSION_TECHSUPPORT
      type: NO_ACCESS
    - resource: PERMISSION_INTERNAL
      type: WRITE_ACCESS
    - resource: PERMISSION_USER
      type: WRITE_ACCESS
    - resource: PERMISSION_ROLE
      type: WRITE_ACCESS
    - resource: PERMISSION_TENANT
      type: WRITE_ACCESS
    - resource: PERMISSION_GSLB
      type: WRITE_ACCESS
    - resource: PERMISSION_GSLBSERVICE
      type: WRITE_ACCESS
    - resource: PERMISSION_AUTOSCALE
      type: WRITE_ACCESS
    - resource: PERMISSION_TRAFFIC_CAPTURE
      type: WRITE_ACCESS
    - resource: PERMISSION_TRAFFICCLONEPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_WAFPOLICY
      type: WRITE_ACCESS
    - resource: PERMISSION_WAFPROFILE
      type: WRITE_ACCESS
    - resource: PERMISSION_USER_CREDENTIAL
      type: WRITE_ACCESS
    - resource: PERMISSION_GSLBGEODBPROFILE
      type: WRITE_ACCESS
