---
- name: Set cluster name
  avi_cluster:
    avi_credentials: "{{ avi_credentials }}"
    api_version: 17.2.13
    name: "{{ cluster_name }}"
    nodes:
      - name: "{{ leader_internal_dns }}"
        ip:
          addr: "{{ leader_internal_dns }}"
          type: "DNS"
        public_ip_or_name:
          addr: "{{ leader_public_ip }}"
          type: "V4"

- name: Common | Wait for cluster
  include_tasks: "common_tasks/wait_cluster_runtime.yml"
