---
- hosts: localhost
  vars:
    avi_credentials:
      controller: "{{ controller }}"
      username: admin
      password: "{{ password }}"
      api_version: 17.2.1
  connection: local
  tasks:
    - name: avi_crendentials
      debug: msg="{{ avi_credentials }}"
    - name: Create pool using avi credentials
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        name: test-pool
        state: "{{ state | default('present') }}"
      register: pool_result
    - debug: msg="{{ pool_result }}"
    - debug: msg="{{ pool_result.api_context }}"
    - name: Create pool reusing session from previous call
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ pool_result.api_context }}"
        name: test-pool
        state: "{{ state | default('present') }}"
        health_monitor_refs:
            - '/api/healthmonitor?name=System-HTTP'
      register: pool_result
