# Create 2 Pools, HTTPPolicySet to direct traffic to each, and Virtual Service
---
- hosts: localhost
  connection: local
  vars:
    avi_credentials:
      controller: "{{ avi_controller }}"
      username: "{{ avi_username }}"
      password: "{{ avi_password }}"
      tenant: admin
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: create pool
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        name: testpool1
        state: present
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: 10.90.130.8
              type: V4
          - ip:
              addr: 10.90.130.7
              type: V4
    - name: create testpool2
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        name: testpool2
        state: present
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: 10.90.132.8
              type: V4
          - ip:
              addr: 10.90.132.7
              type: V4
    - name: create test http policy set
      avi_httppolicyset:
        avi_credentials: "{{ avi_credentials }}"
        name: test-HTTP-Policy-Set
        tenant_ref: /api/tenant/?name={{ tenant }}
        http_request_policy:
          rules:
            - index: 1
              enable: true
              name: test-test1
              match:
                path:
                  match_case: INSENSITIVE
                  match_str:
                    - /test1
                  match_criteria: EQUALS
              switching_action:
                action: HTTP_SWITCHING_SELECT_POOL
                status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
                pool_ref: '/api/pool?name=testpool1'
            - index: 2
              enable: true
              name: test-test2
              match:
                path:
                  match_case: INSENSITIVE
                  match_str:
                    - /test2
                  match_criteria: CONTAINS
              switching_action:
                action: HTTP_SWITCHING_SELECT_POOL
                status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
                pool_ref: '/api/pool?name=testpool2'
        is_internal_policy: false
    - avi_vsvip:
        name: vsvip-newtestvs-Default-Cloud
        avi_credentials: '{{ avi_credentials }}' 
        api_context: '{{avi_api_context | default(omit)}}'
        tenant_ref: /api/tenant/?name={{ tenant }}
        cloud_ref: /api/cloud/?name=Default-Cloud
        state: "{{ state }}"
        vip:
        - vip_id: '1'
          avi_allocated_fip: false
          auto_allocate_ip: false
          enabled: true
          auto_allocate_floating_ip: false
          avi_allocated_vip: false
          auto_allocate_ip_type: V4_ONLY
          ip_address:
            type: V4
            addr: 198.51.100.252
    - name: create virtual service
      avi_virtualservice:
        avi_credentials: "{{ avi_credentials }}"
        name: newtestvs
        state: present
        performance_limits:
          max_concurrent_connections: 1000
        services:
          - port: 443
            enable_ssl: true
          - port: 80
        ssl_profile_ref: '/api/sslprofile?name=System-Standard'
        application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
        ssl_key_and_certificate_refs:
          - '/api/sslkeyandcertificate?name=System-Default-Cert'
        vsvip_ref: /api/vsvip/?name=vsvip-newtestvs-Default-Cloud
        pool_ref: '/api/pool?name=testpool1'
        http_policies:
          - index: 11
            http_policy_set_ref: '/api/httppolicyset?name=test-HTTP-Policy-Set'
