#
# @author: Gaurav Rastogi (grastogi@avinetworks.com)
#
# This playbook remove list of pool servers from a pool
#
# Usage:
#   ansible-playbook  -M network/avi --extra-vars "username=admin password=password controller=10.10.25.42 pool=p1 pool_servers_ip=10.10.10.10,20.20.20.20"
#
---
- hosts: localhost
  connection: local
  vars:
    avi_credentials:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
    pool_name: "{{ pool_name }}"
    pool_servers_ip: "{{ pool_servers }}"
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: build server list
      set_fact:
        servers: "{{ servers|default([]) + [{'ip': {'addr': item, 'type': 'V4'}}] }}"
      with_items: "{{ pool_servers_ip.split(',') }}"
      # each server_list item has ansible fact as server
    - name: get pool information
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: get
        path: pool
        params:
          name: "{{ pool_name }}"
      register: pool_results
    - name: get_pool_path
      set_fact:
        pool_path: pool/{{ pool_results.obj.results[0].uuid }}
    - name: delete servers from pool
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: patch
        path: "{{ pool_path }}"
        data:
          delete:
            servers: "{{ servers }}"
