---
# ansible-playbook user_create.yml -e "master_ctl_ip=10.10.20.10,master_ctl_username=admin,..."
- hosts: localhost
  vars:
    avi_credentials:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
    avi_users:
      - username: vnair
        name: Vivek Nair
        password: test123$%
      - username: grastogi
        name: Gaurav Rastogi
        password: test123$%
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Check if user exists on Avi
      avi_api_session:
        api_version: 17.2.7
        avi_credentials: "{{ avi_credentials }}"
        path: user
        params:
          name: "{{ item.username }}"
      register: user_exists
      with_items:
        - "{{ avi_users }}"
    - name: Existing User
      debug: msg="{{ user_exists }}"

    - name: Create User on Avi
      avi_api_session:
        api_version: 17.2.7
        avi_credentials: "{{ avi_credentials }}"
        http_method: post
        path: user
        data:
          require_password_confirmation: false
          is_active: true
          access:
          - tenant_ref: '/api/tenant?name=admin'
          role_ref: '/api/role?name=System-Admin'
          default_tenant_ref: '/api/tenant?name=admin'
          full_name: "{{ item.item.name }}"
          username: "{{ item.item.username }}"
          password: "{{ item.item.password }}"
          name: "{{ item.item.name }}"
      when: item.obj.count < 1
      with_items:
        - "{{ user_exists.results }}"
