---
- name: "Change admin default password on first controller"
  avi_useraccount:
    controller: "{{ CONTROLLER_IP_1 }}"
    username: "{{ AVI_CREDENTIALS.username }}"
    password: "{{ AVI_CREDENTIALS.password }}"
    api_version: "{{ AVI_CREDENTIALS.api_version }}"
    old_password: "{{ OLD_PASSWORD }}"    
  ignore_errors: yes
