---
- hosts: localhost
  connection: local
  
  vars:
    app_name: app1
    avi_credentials:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      api_version: "{{ api_version }}"
  
  vars_files:
    - "{{ site_dir }}/vars/creds.yml"
  roles:
    - role: "avinetworks.avisdk"
  
  tasks:
    - name: Setting up Application
      debug: msg="{{ app_name }}"
        
    - name: Create health monitor
      avi_healthmonitor:
        avi_credentials: "{{ avi_credentials | default(omit)}}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: app1-hm
        http_monitor:
          http_request: "HEAD / HTTP/1.0"
          http_response_code:
            - HTTP_2XX
            - HTTP_3XX
        receive_timeout: 4
        failed_checks: 3
        send_interval: 10
        successful_checks: 3
        type: HEALTH_MONITOR_HTTP

    - name: Create pool
      avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit)}}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: app1-pool
        lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
        health_monitor_refs:
          - "/api/healthmonitor?name=app1-hm"
        servers:
          - ip:
               addr: "{{ pool_server1 }}"
               type: 'V4'
          - ip:
               addr: "{{ pool_server2 }}"
               type: 'V4'

    - avi_vsvip:
        name: vsvip-{{ app_name }}-Default-Cloud
        avi_credentials: '{{ avi_credentials }}' 
        api_context: '{{avi_api_context | default(omit)}}'
        tenant_ref: '/api/tenant/?name=admin'
        cloud_ref: '/api/cloud/?name=Default-Cloud'
        state: "{{ state }}"
        vip:
        - vip_id: '1'
          avi_allocated_fip: false
          auto_allocate_ip: false
          enabled: true
          auto_allocate_floating_ip: false
          avi_allocated_vip: false
          auto_allocate_ip_type: V4_ONLY
          ip_address:
            type: V4
            addr: "{{ app1_vip }}"

    - name: Create Virtualservice
      avi_virtualservice:
        avi_credentials: "{{ avi_credentials | default(omit)}}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: "{{ app_name }}"
        services:
          - port: 80
        pool_ref: '/api/pool?name=app1-pool'
        vsvip_ref: /api/vsvip/?name=vsvip-{{ app_name }}-Default-Cloud
