avi_config:
  pool:
    - name: app1-pool
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server1 }}"
             type: 'V4'
        - ip:
             addr: "{{ pool_server2 }}"
             type: 'V4'

  vsvip:
    - name: vsvip-app2-Default-Cloud
      vip:
      - enabled: true
        ip_address:
          addr: "{{ app1_vip }}"
          type: V4
        vip_id: '1'

  virtualservice:
    - name: app1
      services:
        - port: 80
      pool_ref: '/api/pool?name=app1-pool'
      vsvip_ref: /api/vsvip/?name=vsvip-app2-Default-Cloud

