---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: avi
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: avirole
  namespace: default
rules:
  - apiGroups:
    - ''
    resources:
    - "*"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - pods
    - replicationcontrollers
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - ingresses
    verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: avirolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: avirole
subjects:
- kind: ServiceAccount
  name: avi
  namespace: default
