- hosts: localhost
  connection: local
  vars_files:
    - "creds_unsecure_using_facts.yml"
  vars:
    app_name: app1
    avi_credentials1:
    avi_credentials2:

  tasks:
    - name: Create or Update Pool
      register: results
      avi_pool:
        controller: "{{ avi_credentials.avi_controller}}"
        username: "{{ avi_credentials.avi_username }}"
        password: "{{ avi_credentials.avi_password }}"
        api_version: "{{ avi_credentials.api_version }}"
        avi_disable_session_cache_as_fact: "{{ avi_credentials.avi_disable_session_cache_as_fact }}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: "{{app_name}}-pool"
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
          - '/api/healthmonitor?name=System-Ping'
        cloud_ref: '/api/cloud?name=Default-Cloud'
        servers:
          - ip:
               addr: '10.90.64.16'
               type: 'V4'
          - ip:
               addr: '10.90.64.14'
               type: 'V4'
      
    - avi_vsvip:
        name: vsvip-{{app_name}}-Default-Cloud
        controller: "{{ avi_credentials.avi_controller}}"
        username: "{{ avi_credentials.avi_username }}"
        password: "{{ avi_credentials.avi_password }}"
        api_version: "{{ avi_credentials.api_version }}"
        api_context: '{{avi_api_context | default(omit)}}'
        tenant_ref: /api/tenant/?name={{ tenant }}
        cloud_ref: /api/cloud/?name=Default-Cloud
        state: "{{ state }}"
        vip:
        - vip_id: '1'
          avi_allocated_fip: false
          auto_allocate_ip: false
          enabled: true
          auto_allocate_floating_ip: false
          avi_allocated_vip: false
          auto_allocate_ip_type: V4_ONLY
          ip_address:
            type: V4
            addr: 198.51.100.222

    - name: Create Virtual Service >= 17
      register: results
      avi_virtualservice:
        controller: "{{ avi_credentials.avi_controller}}"
        username: "{{ avi_credentials.avi_username }}"
        password: "{{ avi_credentials.avi_password }}"
        api_version: "{{ avi_credentials.api_version }}"
        avi_disable_session_cache_as_fact: "{{ avi_credentials.avi_disable_session_cache_as_fact }}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: "{{app_name}}"
        pool_ref: "/api/pool?name={{app_name}}-pool"
        cloud_ref: '/api/cloud?name=Default-Cloud'
        vsvip_ref: /api/vsvip/?name=vsvip-{{app_name}}-Default-Cloud
        services:
          - port: 4242
          
    - name: Create or Update Pool on controller 2
      register: results2
      avi_pool:
        controller: "{{ avi_credentials.avi_controller2}}"
        username: "{{ avi_credentials.avi_username }}"
        password: "{{ avi_credentials.avi_password }}"
        api_version: "{{ avi_credentials.api_version }}"
        avi_disable_session_cache_as_fact: "{{ avi_credentials.avi_disable_session_cache_as_fact }}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: "{{app_name}}-pool"
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
          - '/api/healthmonitor?name=System-Ping'
        cloud_ref: '/api/cloud?name=Default-Cloud'
        servers:
          - ip:
               addr: '10.90.64.16'
               type: 'V4'
          - ip:
               addr: '10.90.64.14'
               type: 'V4'
    
    - avi_vsvip:
        name: vsvip-{{app_name}}-Default-Cloud
        controller: "{{ avi_credentials.avi_controller2}}"
        username: "{{ avi_credentials.avi_username }}"
        password: "{{ avi_credentials.avi_password }}"
        api_version: "{{ avi_credentials.api_version }}"
        api_context: '{{avi_api_context | default(omit)}}'
        tenant_ref: /api/tenant/?name={{ tenant }}
        cloud_ref: /api/cloud/?name=Default-Cloud
        state: "{{ state }}"
        vip:
        - vip_id: '1'
          avi_allocated_fip: false
          auto_allocate_ip: false
          enabled: true
          auto_allocate_floating_ip: false
          avi_allocated_vip: false
          auto_allocate_ip_type: V4_ONLY
          ip_address:
            type: V4
            addr: 198.51.100.222
      
    - name: Create Virtual Service on controller 2
      register: results2
      avi_virtualservice:
        controller: "{{ avi_credentials.avi_controller2}}"
        username: "{{ avi_credentials.avi_username }}"
        password: "{{ avi_credentials.avi_password }}"
        api_version: "{{ avi_credentials.api_version }}"
        avi_disable_session_cache_as_fact: "{{ avi_credentials.avi_disable_session_cache_as_fact }}"
        api_context: "{{avi_api_context | default(omit)}}"
        name: "{{app_name}}"
        pool_ref: "/api/pool?name={{app_name}}-pool"
        cloud_ref: '/api/cloud?name=Default-Cloud'
        vsvip_ref: /api/vsvip/?name=vsvip-{{app_name}}-Default-Cloud
        services:
          - port: 4242
      
    