- hosts: localhost
  connection: local
  collections:
    - vmware.alb  
  vars_files:
     variables.yml
  tasks:
  - include_vars: variables.yml
  #Get User data JSON Object
  - name: Get user data
    avi_api_session:
      controller: "{{ CONTROLLER_CLUSTER_IP }}"
      username: "{{ AVI_CREDENTIALS.username }}"
      password: "{{ AVI_CREDENTIALS.password }}"
      api_version: "{{ AVI_CREDENTIALS.api_version }}"
      http_method: get
      path: user
      params:
        name: "{{ AVI_USER }}"
    register: user_results 
    when: AVI_USER != "admin"
  #Update Password for NOT admin User  
  - name: "Change user password"
    avi_user:
      avi_credentials:
        controller: "{{ CONTROLLER_CLUSTER_IP }}"
        username: "{{ AVI_CREDENTIALS.username }}"
        password: "{{ AVI_CREDENTIALS.password }}"
        api_version: "{{ AVI_CREDENTIALS.api_version }}"
      avi_api_update_method: put
      name: "{{ user_results.obj.results.0.full_name }}"
      obj_password: "{{ AVI_PASSWORD }}"
      obj_username: "{{ AVI_USER }}"
    when: AVI_USER != "admin"
  #Update Password for admin User 
  - name: "Change admin password"
    avi_useraccount:
      controller: "{{ CONTROLLER_CLUSTER_IP }}"
      username: "admin"
      password: "{{ AVI_PASSWORD }}"
      api_version: "{{ AVI_CREDENTIALS.api_version }}"
      old_password: "{{ AVI_ADMIN_CURRENT_PASSWORD }}"
    when: AVI_USER == "admin"
