---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Required Variables / NSX-T Password Change
# Description: This are the main variables required for NSXT Cloud Password Change.
# --------------------------------------------------------------------

# NSX-T and vCenter Credentials Information
NSXT_CLOUDCONNECTORUSER: <NSX-T Cloud Connector User Object Name> #If only changing vCenter password then comment line.
NSXT_PASSWORD: <New NSX-T Cloud Connector Password> #If only changing vCenter password then comment line.
NSXT_VCENTER_CLOUDCONNECTORUSER: <vCenter Cloud Connector User Object Name> #If only changing NSX-T password then comment line.
NSXT_VCENTER_PASSWORD: <New vCenter Cloud Connector Password> #If only changing NSX-T password then comment line.



# --------------------------------------------------------------------
# Required Variables / Avi User Password Change
# Description: This are the main variables required for Avi User Password Change.
# --------------------------------------------------------------------

# Avi User Credentials Information
AVI_USER: <Avi Username>
AVI_PASSWORD: <New Avi User Password>
AVI_ADMIN_CURRENT_PASSWORD: <Current Avi admin Password> #If not updating admin password then comment line.
