---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Enviroment Variables / Controller Deployments
# Description: You only have to apply variables on the installation type you desire.
# --------------------------------------------------------------------

# Vmware vCenter Credentials and Other Parameters
VCENTER_HOST: <vCenter FQDN/IP Address>
VCENTER_USER: <vCenter Username>
VCENTER_PASSWORD: <vCenter User Password>
DATACENTER: <vCenter Datacenter Name>
VMWARE_CLUSTER_NAME: <vCenter Cluster Name>
VMWARE_DATASTORE: <vCenter Datastore Name>
CON_FOLDER: <vCenter VM Folder Name> #if nested folder then give full path - EX. Network/NSXALB"
CON_MGMT_PORTGROUP: <vCenter Port Group Name>
OVFTOOL_PATH: <OVF Tool Install Path> #Linux Default Install Path is "/usr/bin" -  DownloadLink: https://code.vmware.com/web/tool/4.4.0/ovf

# Controller OVA Image Location
OVA_PATH: <Avi Controller OVA File Path>
