---
- gather_facts: 'false'
  hosts: all
  roles:
  - role: avinetworks.avise
    se_cloud_name: Default-Cloud
    se_csp_default_gw: 10.128.2.1
    se_csp_disk_size: 100
    se_csp_memory_gb: 2
    se_csp_mgmt_ip: 10.128.2.193
    se_csp_mgmt_mask: 255.255.255.0
    se_csp_num_cpu: 1
    se_csp_password: "{{csp_password}}"
    se_csp_qcow_image_file: /tmp/Smoke-Ctlr-I.qcow2
    se_csp_service_name: grastogi-temp
    se_csp_user: admin
    se_csp_vnics:
    - network_name: enp1s0f0
      nic: 0
      tagged: 'false'
      type: access
    se_deploy_type: csp
    se_master_ctl_ip: 10.10.25.42
    se_master_ctl_password: "{{avi_password}}"
    se_master_ctl_username: admin
    se_tenant: admin
