---
- hosts: all
  gather_facts: false
  roles:
    - role: avinetworks.avise
      se_deploy_type: csp
      se_master_ctl_ip: 10.128.2.18
      se_master_ctl_username: admin
      se_master_ctl_password: AviNetworks123!
      se_csp_user: admin
      se_csp_password: AviCsp@2100
      se_csp_qcow_image_file: ERIC_SE.qcow2
      se_csp_mgmt_ip: 10.128.2.20
      se_csp_mgmt_mask: 255.255.255.0
      se_csp_default_gw: 10.128.2.1
      se_csp_service_name: eric-se
      se_csp_memory: 16384
