# Simple application name foo
# It has following characterstics
# Pool with two servers and HTTP health monitor
# Single VIP
# HTTP application
---
- hosts: localhost
  connection: local
  vars_files:
    - "vars/creds_unsecure.yml"
  vars:
    avi_credentials:
      controller: "{{ avi_controller }}"
      username: "{{ avi_username }}"
      password: "{{ avi_password }}"
  tasks:
    - name: Create or Update Pool
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ api_version }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ app_name }}-pool"
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
          - '/api/healthmonitor?name=System-Ping'
        cloud_ref: '/api/cloud?name=Default-Cloud'
        servers:
          - ip:
               addr: '10.90.64.16'
               type: 'V4'
          - ip:
               addr: '10.90.64.14'
               type: 'V4'

    - name: Create VS Vip for VS >= 17
      avi_vsvip:
        name: vsvip-"{{ app_name }}"-Default-Cloud
        avi_credentials: '{{ avi_credentials }}' 
        api_context: '{{avi_api_context | default(omit)}}'
        tenant_ref: /api/tenant/?name={{ tenant }}
        cloud_ref: /api/cloud/?name=Default-Cloud
        state: "{{ state }}"
        vip:
        - vip_id: '1'
          avi_allocated_fip: false
          auto_allocate_ip: false
          enabled: true
          auto_allocate_floating_ip: false
          avi_allocated_vip: false
          auto_allocate_ip_type: V4_ONLY
          ip_address:
            type: V4
            addr: 198.51.100.222
      when:
        - api_version >= "17"

    - name: Create Virtual Service >= 17
      avi_virtualservice:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ api_version }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ app_name }}"
        pool_ref: "/api/pool?name={{ app_name }}-pool"
        cloud_ref: '/api/cloud?name=Default-Cloud'
        vsvip_ref: /api/vsvip/?name=vsvip-"{{ app_name }}"-Default-Cloud
        services:
          - port: 4242
      when:
        - api_version >= "17"

    - name: Create Virtual Service < 17
      avi_virtualservice:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ api_version }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ app_name }}"
        pool_ref: "/api/pool?name={{ app_name }}-pool"
        cloud_ref: '/api/cloud?name=Default-Cloud'
        ip_address:
          addr: '10.90.64.222'
          type: 'V4'
        services:
          - port: 80
      when:
        - api_version < "17"
