{
 "title": "01-Summary",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\" WHERE location =~ /$location/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"avicontroller\" WHERE location =~ /$location/ AND environment =~ /$environment/"
   }
  ]
 },
 "panels": [
  {
   "title": "VS UP",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "status_up",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_up" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.status_up, 'VS Up')"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_new_established_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns), 'connections')"
    }
   ]
  },
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"l7_client.avg_ssl_handshakes_new\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"environment\" =~ /^$environment$/ AND \"location\" =~ /^$location$/ AND \"metric_type\" = 'virtualservice_metrics') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_bandwidth",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"l7_client.avg_ssl_handshakes_new\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"environment\" =~ /^$environment$/ AND \"location\" =~ /^$location$/ AND \"metric_type\" = 'virtualservice_metrics') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'Total SE Bandwidth')"
    }
   ]
  },
  {
   "title": "Controller CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cluster_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster_node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_stats.avg_cpu_usage",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"controller_stats.avg_mem_usage\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"environment\" =~ /^$environment$/ AND \"location\" =~ /^$location$/ AND \"metric_type\" = 'controller_metrics') AND $timeFilter GROUP BY time($__interval), \"cluster_node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "controller_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "Controller Mem%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cluster_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster_node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "controller_stats.avg_mem_usage",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"controller_stats.avg_mem_usage\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"environment\" =~ /^$environment$/ AND \"location\" =~ /^$location$/ AND \"metric_type\" = 'controller_metrics') AND $timeFilter GROUP BY time($__interval), \"cluster_node\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "controller_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.controller.*.controller_stats_avg_mem_usage, 6)"
    }
   ]
  },
  {
   "title": "Total Number of VS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Virtual Services Configured",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_count" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.vs_count), 'Virtual Services Deployed')"
    },
    {
     "alias": "Virtual Services Deployed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vs_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_vs_count" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.count, 'Virtual Services Configured')"
    }
   ]
  },
  {
   "title": "Total Number of Service Engines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Service Engines",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_count" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.serviceengine.count, 'Service Engines')"
    }
   ]
  },
  {
   "title": "Avi Version - Current Version = 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_version",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "version" }
     ],
     "target": "aliasByNode(currentAbove(network-script.avi.$location.$environment.$device.current_version.*, 0), 6)"
    }
   ]
  },
  {
   "title": "Total Virtual Server Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VS Up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status_up",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_up" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.status_up, 'VS Up')"
    },
    {
     "alias": "VS Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status_down",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_down" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.status_down, 'VS Down')"
    }
   ]
  },
  {
   "title": "Top 5 SE CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.*.se_stats_avg_cpu_usage, 5), 6)"
    }
   ]
  },
  {
   "title": "Total VS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Total RX Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_rx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(scale(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_rx_bytes), 8), 'Total RX Bandwidth')"
    },
    {
     "alias": "Total TX Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_tx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(scale(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_tx_bytes), 8), 'Total TX Bandwidth')"
    }
   ]
  },
  {
   "title": "Total Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_new_established_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_new_established_conns), 'connections')"
    }
   ]
  },
  {
   "title": "Total Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_complete_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.virtualservice.*.l4_client_avg_complete_conns), ' connections')"
    }
   ]
  },
  {
   "title": "Active Cluster Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "active_members",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "cluster" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.cluster.active_members)"
    }
   ]
  },
  {
   "title": "Cluster Roles: 1 == Leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Role" }
   ],
   "targets": [
    {
     "alias": "$tag_cluster_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "member_role",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "cluster" }
     ],
     "target": "aliasByNode(netwhttps://10.144.73.9:3000/#ork-script.avi.$location.$environment.$device.cluster.*.role, 6)"
    }
   ]
  },
  {
   "title": "Network Pool Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_network_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "network_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "network_usage" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "% of Licensed Cores Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "percentage_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "licensing" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.licensing.percentage_used)"
    }
   ]
  },
  {
   "title": "TOTAL SE BW",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Total SE Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "alias(sumSeries(network-script.avi.$location.$environment.$device.serviceengine.*.se_if_avg_bandwidth), 'Total SE Bandwidth')"
    }
   ]
  }
 ]
}