{
 "title": "03-Service Engine Specific",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\" WHERE location =~ /$location/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"avicontroller\" WHERE location =~ /$location/ AND environment =~ /$environment/"
   },
   {
    "name": "serviceengine",
    "query": "SHOW TAG VALUES WITH KEY = \"se_name\" WHERE location =~ /$location/ AND environment =~ /$environment/ AND avicontroller =~ /$device/"
   }
  ]
 },
 "panels": [
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"l7_client.avg_ssl_handshakes_new\" WHERE (\"avicontroller\" =~ /^$device$/ AND \"location\" =~ /^$location$/ AND \"environment\" =~ /^$environment$/ AND \"se_name\" =~ /^$serviceengine$/ AND \"metric_type\" = 'virtualservice_metrics_per_serviceengine') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      }
     ],
     "target": "sumSeries(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_new_established_conns",
     "query": "SELECT mean(\"value\") FROM \"l4_client.avg_complete_conns\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      }
     ],
     "target": "network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_connections"
    }
   ]
  },
  {
   "title": "Concurrent Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.max_open_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      }
     ],
     "target": "sumSeries(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l4_client_max_open_conns)"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_cpu_usage"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthscore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_healthscore" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.healthscore, 6)"
    }
   ]
  },
  {
   "title": "SE Average Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "avg tx bw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_tx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "alias(scale(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_tx_bytes, 8), 'avg tx bw')"
    },
    {
     "alias": "avg rx bw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_rx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "alias(scale(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_rx_bytes, 8), 'avg rx bw')"
    }
   ]
  },
  {
   "title": "SE CPU%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_cpu_usage, 6)"
    }
   ]
  },
  {
   "title": "VS per SE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vs_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_vs_count" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.vs_count, 6)"
    }
   ]
  },
  {
   "title": "SE Healthscore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthscore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "serviceengine_healthscore" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.healthscore, 6)"
    }
   ]
  },
  {
   "title": "SE RX PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_rx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "SE TX PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_if.avg_tx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_if_avg_tx_pkts, 6)"
    }
   ]
  },
  {
   "title": "SE CPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_connections, 6)"
    }
   ]
  },
  {
   "title": "VS Capacity Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vs_capacity_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_capacity" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.vs_capacity_used, 6)"
    }
   ]
  },
  {
   "title": "SE Missed Heartbeats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "missed_heartbeats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      {
       "condition": "AND",
       "key": "metric_type",
       "operator": "=",
       "value": "serviceengine_missed_heartbeats"
      }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.missed_heartbeats, 6)"
    }
   ]
  },
  {
   "title": "Per VS Client BW - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      {
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l4_client_avg_bandwidth, 10), 8)"
    }
   ]
  },
  {
   "title": "Per VS SSL TPS - Top 10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      {
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l7_client_avg_ssl_handshakes_new, 10), 8)"
    }
   ]
  },
  {
   "title": "Connection Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "se_stats.avg_connection_mem_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "serviceengine_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.se_stats_avg_connection_mem_usage, 6)"
    }
   ]
  },
  {
   "title": "Per VS - Client Side Open Conns - Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.max_open_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10" ], "type": "top" }
      ]
     ],
     "tags": [
      {
       "key": "metric_type",
       "operator": "=",
       "value": "virtualservice_metrics_per_serviceengine"
      },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "se_name", "operator": "=~", "value": "/^$serviceengine$/" }
     ],
     "target": "aliasByNode(highestCurrent(network-script.avi.$location.$environment.$device.serviceengine.$serviceengine.virtualservice_stats.*.l4_client_max_open_conns, 10), 8)"
    }
   ]
  }
 ]
}