{
 "title": "05-Virtual Services Specific",
 "tags": [
  "network",
  "avi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\" WHERE location =~ /$location/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY = \"avicontroller\" WHERE location =~ /$location/ AND environment =~ /$environment/"
   },
   {
    "name": "vs",
    "query": "SHOW TAG VALUES WITH KEY = \"vs_name\" WHERE location =~ /$location/ AND environment =~ /$environment/ AND avicontroller =~ /$device/"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_new_established_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns"
    }
   ]
  },
  {
   "title": "Concurrent Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_complete_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns"
    }
   ]
  },
  {
   "title": "SSL TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_handshakes_new)"
    }
   ]
  },
  {
   "title": "Healthscore",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthscore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_healthscore" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore)"
    }
   ]
  },
  {
   "title": "End to End Timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Client RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_total_rtt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_total_rtt, 'Client RTT')"
    },
    {
     "alias": "Server RTT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_total_rtt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_server_avg_total_rtt, 'Server RTT')"
    },
    {
     "alias": "App Response",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_server.avg_application_response_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_application_response_time, 'App Rsponse')"
    },
    {
     "alias": "Data Transfer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_client_data_transfer_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "alias(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_client_data_transfer_time, 'Data Transfer')"
    }
   ]
  },
  {
   "title": "VS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_bandwidth, 6)"
    }
   ]
  },
  {
   "title": "Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_new_established_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_new_established_conns, 6)"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_complete_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_complete_conns, 6)"
    }
   ]
  },
  {
   "title": "VS Oper Status : 1 == UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oper_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_operstatus" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.oper_status)"
    }
   ]
  },
  {
   "title": "Avg Server Side Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_server.avg_resp_latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_server_avg_resp_latency)"
    }
   ]
  },
  {
   "title": "Pool Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name : pool_members_configured",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualservice_pool_members",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_pool_members" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members_up, 8, 9)"
    },
    {
     "alias": "$tag_pool_name : pool_members_enabled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualservice_pool_members_enabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_pool_members" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members_enabled, 8, 9)"
    },
    {
     "alias": "$tag_pool_name : pool_members_up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualservice_pool_members_up",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_pool_members" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.pool_members, 8, 9)"
    }
   ]
  },
  {
   "title": "RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_rx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_rx_pkts, 6)"
    }
   ]
  },
  {
   "title": "TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_tx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_tx_pkts, 6)"
    }
   ]
  },
  {
   "title": "VS Healthscore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthscore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_healthscore" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.healthscore, 6)"
    }
   ]
  },
  {
   "title": "Hosted on Service Engines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_se_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "se_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hosting_se",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_hosted_se" }
     ],
     "target": "aliasByMetric(currentAbove(network-script.avi.$location.$environment.$device.virtualservice.$vs.serviceengine.*, 0))"
    }
   ]
  },
  {
   "title": "Average Client Lossy Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.avg_lossy_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_avg_lossy_connections)"
    }
   ]
  },
  {
   "title": "SSL Statistics /sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_handshakes_new",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_handshakes_new)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_ssl_connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_ssl_connections)"
    }
   ]
  },
  {
   "title": "4xx 5xx Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_resp_4xx_avi_errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx_avi_errors)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_resp_5xx_avi_errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx_avi_errors)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_resp_4xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx_avi_errors)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.avg_resp_5xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l7_client_avg_resp_4xx_avi_errors)"
    }
   ]
  },
  {
   "title": "Client Side Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.max_open_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_max_open_conns)"
    }
   ]
  },
  {
   "title": "Virtual Service ApDex  Values",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_client.apdexc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_apdexc)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.apdexc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_apdexc)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_client.apdexr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_apdexc)"
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l7_server.apdexr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "virtualservice_metrics" }
     ],
     "target": "aliasByMetric(network-script.avi.$location.$environment.$device.virtualservice.$vs.l4_client_apdexc)"
    }
   ]
  },
  {
   "title": "Pool Member - Avg Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name : $tag_pool_member",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_member" ], "type": "tag" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_bandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "pool_member_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_bandwidth, 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Open Conns",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name : $tag_pool_member",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_member" ], "type": "tag" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_open_conns",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "pool_member_metrics" }
     ],
     "target": "aliasByNode(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_open_conns, 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total TX packets from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "$tag_pool_name : $tag_pool_member",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_member" ], "type": "tag" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_tx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "pool_member_metrics" }
     ],
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_tx_pkts, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total RX packets from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "targets": [
    {
     "alias": "$tag_pool_name : $tag_pool_member",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_member" ], "type": "tag" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_rx_pkts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "pool_member_metrics" }
     ],
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_rx_pkts, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total TX Bytes to",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "targets": [
    {
     "alias": "$tag_pool_name : $tag_pool_member",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_member" ], "type": "tag" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_tx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "pool_member_metrics" }
     ],
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_tx_bytes, 60), 8, 9)"
    }
   ]
  },
  {
   "title": "Pool Member - Total RX Bytes from",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "alias": "$tag_pool_name : $tag_pool_member",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_member" ], "type": "tag" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l4_server.avg_rx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "avicontroller", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "vs_name", "operator": "=~", "value": "/^$vs$/" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "pool_member_metrics" }
     ],
     "target": "aliasByNode(scale(network-script.avi.$location.$environment.$device.virtualservice.$vs.pool.*.*.l4_server_avg_rx_bytes, 60), 8, 9)"
    }
   ]
  }
 ]
}