---
# --------------------------------------------------------------------
# Management Variables
# Description: This are variables used for any type of ansible deployment.
# --------------------------------------------------------------------
# Cluster IP for Avi Controller
CONTROLLER_CLUSTER_IP: <Controller Cluster/Node IP> # This can be either cluster ip or the ip of the leader controller.

# Controller Credentials
AVI_CREDENTIALS:
  controller: "{{ CONTROLLER_CLUSTER_IP }}" 
  username: <Avi Username>
  password: <Avi User Password>
  api_version: <Avi Controller Version> #Ex. "22.1.3"

# --------------------------------------------------------------------
# Required Variables / Controller Deployments
# Description: This are the main variables required for controller deployments.
# --------------------------------------------------------------------

# Controller Name and IP Addresses
CONTROLLER_IP_1: <Node 1 IP Address>
CONTROLLER_NAME_1: <Node 1 Name>
CONTROLLER_IP_2: <Node 2 IP Address>
CONTROLLER_NAME_2: <Node 2 Name>
CONTROLLER_IP_3: <Node 3 IP Address>
CONTROLLER_NAME_3: <Node 3 Name>
CLUSTER_NAME: <Avi Cluster Name> #Ex. "cluster01"

# Controller Default Password
OLD_PASSWORD: "58NFaGDJm(PJH0G" #Found on download image page

# Controller Configuration Details
DNS_SERVERS: [<Comma Seperated IP List] #Ex. [1.1.1.1,2.2.2.2,3.3.3.3]
NTP_SERVERS: [<Comma Seperated FQDN/IP List] #Ex. [1.1.1.1,2.2.2.2,3.3.3.3] or [dns1.avi.com,dns2.avi.com]
NTP_TYPE: "V4"  #If servers are hostname use type "DNS", if IP use type "V4" 
BACKUP_PASSPHRASE: <Backup Passphrase> 
REMOTE_BACKUP_USER: <Remote Backup User> #Username on destination server
REMOTE_BACKUP_PASSWORD: <Remote Backup User Password>
BACKUP_TO_REMOTE_HOST: <no/yes> #If Backup to Remote Host then use yes. Otherwise, if Backup to Localhost then use no.
REMOTE_BCKUP_DIR: <Remote Backup Directory> #Ex "/root"
REMOTE_BACKUP_HOST: <Remote Backup Host IP Address>
LICENSE_FILE: <Avi License File Location> #If using VMWare License Key then comment this line.
SERIAL_KEY: <VMWare License Key> #If using Avi License File then comment this line.
SMTP_SERVER_TYPE: <SMTP Server Type - SMTP_LOCAL_HOST / SMTP_SERVER> #Can be either "SMTP_LOCAL_HOST" or "SMTP_SERVER"
SMTP_FROM_EMAIL: <SMTP From Email Address>
SMTP_SERVER_NAME: <SMTP Remote Server Name> #If SMTP_SERVER_TYPE is set to "SMTP_LOCAL_HOST" then comment this line.
SMTP_SERVER_PORT: <SMTP Remote Server Port> #If SMTP_SERVER_TYPE is set to "SMTP_LOCAL_HOST" then comment this line.
SMTP_USERNAME: <SMTP Remote Server Username> #If SMTP_SERVER_TYPE is set to "SMTP_LOCAL_HOST" then comment this line.
SMTP_PASSWORD: <SMTP Remote Server User Password> #If SMTP_SERVER_TYPE is set to "SMTP_LOCAL_HOST" then comment this line.
SMTP_DISABLE_TLS: <Disable SMTP TLS - true / false>

# --------------------------------------------------------------------
# Enviroment Variables / Controller Deployments
# Description: You only have to apply variables on the installation type you desire.
# --------------------------------------------------------------------

# Controller Management Network Setup
CON_MGMT_PORTGROUP: <vCenter Port Group Name>
CON_MGMT_MASK: <Avi Controller Node Network Mask>
CON_DEFAULT_GW: <Avi Controller Node Default Gateway>

# Vmware vCenter Credentials and Other Parameters
VCENTER_HOST: <vCenter FQDN/IP Address>
VCENTER_USER: <vCenter Username>
VCENTER_PASSWORD: <vCenter User Password>
DATACENTER: <vCenter Datacenter Name>
VMWARE_CLUSTER_NAME: <vCenter Cluster Name>
VMWARE_DATASTORE: <vCenter Datastore Name>
CON_FOLDER: <vCenter VM Folder Name> #if nested folder then give full path - EX. Network/NSXALB"
OVFTOOL_PATH: <OVF Tool Install Path> #Linux Default Install Path is "/usr/bin" -  DownloadLink: https://code.vmware.com/web/tool/4.4.0/ovf

# Controller OVA Image Location
OVA_PATH: <Avi Controller OVA File Path>
