avi_config:
  pool:
    - name: app1-pool
      #state: absent
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server1 }}"
             type: 'V4'
        - ip:
             addr: "{{ pool_server2 }}"
             type: 'V4'
  vsvip:
    - cloud_ref: /api/cloud?name=Default-Cloud
      east_west_placement: false
      name: vsvip-app1-Default-Cloud
      tenant: admin
      tenant_ref: /api/tenant/?name=admin
      vip:
      - auto_allocate_floating_ip: false
        auto_allocate_ip: false
        avi_allocated_fip: false
        avi_allocated_vip: false
        enabled: true
        ip_address:
          addr: "{{ app1_vip }}"
          type: V4
        vip_id: '1'
      vrf_context_ref: /api/vrfcontext/?name=global

  virtualservice:
    - name: app1
      services:
        - port: 80
      pool_ref: '/api/pool?name=app1-pool'
      #pool_ref:
      #  state: absent
      vsvip_ref: /api/vsvip/?name=vsvip-app1-Default-Cloud
